# Generated by Django 5.0.6 on 2024-06-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Avatar',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Verify_Code',
            new_name='verify_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Email',
        ),
    ]
