# Generated by Django 5.1 on 2024-09-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0009_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='توکن'),
            preserve_default=False,
        ),
    ]
