# Generated by Django 5.1 on 2024-09-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0010_alter_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
