# Generated by Django 5.0.6 on 2024-07-10 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم')),
                ('titleForUrl', models.CharField(max_length=200, verbose_name='اسم در آدرس')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Product_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=185, verbose_name='اسم محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('ShortDes', models.CharField(max_length=285, null=True, verbose_name='توضیحات(کوتاه)')),
                ('LongDes', models.TextField(null=True, verbose_name='توضیحات')),
                ('IsDelete', models.BooleanField(default=False, verbose_name='پاک شده / پاک نشده')),
                ('IsActive', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('slug', models.SlugField(allow_unicode=True, default='', unique=True, verbose_name='عنوان در مرورگر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product_category', verbose_name='دسته بندی')),
                ('tag', models.ManyToManyField(to='product_module.product_tag', verbose_name='برچسب ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
