# Generated by Django 5.1 on 2024-09-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_product_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='image',
            field=models.ImageField(upload_to='images/P-images', verbose_name='تصویر'),
        ),
    ]
