# Generated by Django 5.1 on 2024-09-07 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_alter_productcomment_model_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment_model',
            name='parent',
        ),
        migrations.AddField(
            model_name='productcomment_model',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productcomment_model', verbose_name='والد'),
        ),
    ]
