# Generated by Django 5.1 on 2024-09-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_remove_productcomment_model_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_model',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product_model',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Product_Category',
        ),
        migrations.DeleteModel(
            name='Product_Tag',
        ),
    ]
