# Generated by Django 5.1 on 2024-08-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting_module', '0002_slidermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidermodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
    ]
