# Generated by Django 5.1 on 2024-09-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting_module', '0003_slidermodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
    ]
