# Generated by Django 5.1 on 2024-09-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting_module', '0004_sitesettingmodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidermodel',
            name='image',
            field=models.ImageField(upload_to='images/sliders', verbose_name='تصویر اسلاید'),
        ),
    ]
