# Generated by Django 5.1 on 2024-09-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting_module', '0005_alter_slidermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='location',
            field=models.CharField(default=1, max_length=200, verbose_name='مکان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesettingmodel',
            name='logo',
            field=models.ImageField(upload_to='images/logos', verbose_name='لوگو'),
        ),
    ]
