# Generated by Django 5.1 on 2024-09-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0003_alter_articlemodel_short_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='image',
            field=models.ImageField(upload_to='images/Article-images', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='short_des',
            field=models.CharField(max_length=600, verbose_name='توضیحات کوتاه'),
        ),
    ]
